/**
 * The building, drawn rather than traced.
 *
 * GENERATED by scripts/read-floorplan.mjs from src/data/floorplan.svg - do not
 * hand-edit. To take a new version of the drawing: replace that SVG and re-run
 * the script.
 *
 * The three layers are the drawing's own, and so are their weights: the outside
 * of the building, the partitions inside it, and the stairs, which are drawn
 * lightest because they are a thing you walk on rather than a thing you cannot
 * walk through. Doorways are pen-ups in the path data - the absence IS the
 * door, which is also how the building works.
 */
export type Floor = 'upstairs' | 'downstairs';
export type Layer = 'exterior' | 'interior' | 'stairs';
export type Pt = readonly [number, number];

/** Stroke weights, in the drawing's own units, exactly as it sets them. */
export const STROKE: Record<Layer, number> = {
  exterior: 6,
  interior: 3,
  stairs: 1.5,
};

export type FloorPlan = {
  /** The drawing stacks the floors; this is the second one's own shift. */
  offsetY: number;
  /** The floorplate, with the doorways closed up, for the fill underneath. */
  outline: Pt[];
  /** Both floors share a width and a height, so they render at one scale. */
  viewBox: string;
  d: Record<Layer, string>;
};

export const FLOORPLAN: Record<Floor, FloorPlan> = {
  upstairs: {
    offsetY: 0,
    viewBox: "135 15.7 731.7 338.2",
    outline: [
      [333.5, 340],
      [285, 340],
      [187, 340],
      [181, 340],
      [181, 29.6],
      [854.7, 29.6],
      [854.7, 340],
      [360.9, 340],
    ],
    d: {
      exterior: "M333.5 340 H285 M187 340 H181 V29.6 H854.7 V340 H360.9",
      interior: "M290 29.6 V198.3 M290 216.7 V340 M290 244.9 H320.3 V315.6 M320.3 334 V340 M290 96.5 H319.8 M338.2 96.5 H394.2 M394.2 29.6 V205 H336 M375.6 252.2 H394.2 V312.9 M320.3 301 H326 M344.4 301 H394.2 M394.2 312.9 H759.3 M442.2 181.8 H627.7 M442.2 169 V186 M394.2 177 H411.5 M411.5 168 V185.3 M548.1 29.6 V132.3 M548.1 150.7 V212.3 M548.1 230.7 V269.3 M548.1 287.7 V312.9 M548.1 83.5 H579.8 M598.2 83.5 H627.7 M627.7 29.6 V87.5 M627.7 109.3 V242 M548.1 113.3 H627.7 M548.1 242 H627.7 M627.7 155 H677.15 M627.7 198.3 H677.15 M674 155 V158.6 M674 177 V198.3 M695.55 155 H749.45 M742.3 155 V207 M695.55 198.3 H742.3 M698.7 155 V158.6 M698.7 177 V198.3 M742.3 225.4 V233.4 H762.7 M759.3 233.4 V312.9 M767.85 155 H854.7 M791.6 180.2 V199.55 M791.6 217.95 V233.4 M791.6 180.2 H829.5 V233.4 M781.1 233.4 H854.7",
      stairs: "M290 245 H320.3 V314 H290 Z M290 251.3 H320.3 M290 257.6 H320.3 M290 263.9 H320.3 M290 270.2 H320.3 M290 276.5 H320.3 M290 282.8 H320.3 M290 289.1 H320.3 M290 295.4 H320.3 M290 301.7 H320.3 M290 308 H320.3 M791.6 155 H829.5 V180.2 H791.6 Z M797.9 155 V180.2 M804.2 155 V180.2 M810.5 155 V180.2 M816.8 155 V180.2 M823.1 155 V180.2 M829.5 180.2 H854.7 V233.4 H829.5 Z M829.5 186.5 H854.7 M829.5 192.8 H854.7 M829.5 199.1 H854.7 M829.5 205.4 H854.7 M829.5 211.7 H854.7 M829.5 218 H854.7 M829.5 224.3 H854.7 M829.5 230.6 H854.7",
    },
  },
  downstairs: {
    offsetY: 50,
    viewBox: "135 417 731.7 338.2",
    outline: [
      [290, 379],
      [854.4, 379],
      [854.4, 384.4],
      [802.4, 436.4],
      [810.7, 444.7],
      [830.1, 464.1],
      [854.4, 488.4],
      [854.4, 693.2],
      [290, 693.2],
    ],
    d: {
      exterior: "M290 379 H854.4 V384.4 L802.4 436.4 L810.7 444.7 M830.1 464.1 L854.4 488.4 V693.2 H290 V379",
      interior: "M547.3 379 V562.4 H563.55 M497.1 406.6 V490.6 M497.1 518.2 V550.2 H547.3 M581.95 562.4 H670.2 M598.2 379 V562.4 M598.2 455.7 H670.2 M598.2 500.9 H670.2 M670.2 379 V418.3 M670.2 436.7 V479.8 M670.2 498.2 V539.3 M670.2 557.7 V562.4 M290 561.8 H329.5 M290 636.6 H316.8 M316.8 586.2 H329.5 M395.1 586.2 H409.15 M427.55 586.2 H474 M492.4 586.2 H503.95 M497.7 586.2 V605 H528.6 V586.2 M522.35 586.2 H626.65 M645.05 586.2 H717.7 M736.1 586.2 H741.7 M741.7 598 H758 M776.4 598 H782 V586.2 H854.4 M316.8 586.2 V666.9 M316.8 685.3 V693.2 M395.1 586.2 V693.2 M468.7 586.2 V693.2 M559.2 586.2 V666.9 M559.2 685.3 V693.2 M468.7 659 H651.8 M651.8 586.2 V666.9 M651.8 685.3 V693.2 M741.7 586.2 V666.9 M741.7 685.3 V693.2 M802.4 436.4 L743 495.8 V525.3 H711.4 M817.3 379 L820.5 384.5 M829.7 400.4 L832.9 405.9 M854.4 488.4 L810.8 532 M791.6 541 V532 H827.6 M791.6 559.4 V562.5 M791.6 562.5 H829",
      stairs: "M290 586.2 H316.8 V636.6 H290 Z M290 592.5 H316.8 M290 598.8 H316.8 M290 605.1 H316.8 M290 611.4 H316.8 M290 617.7 H316.8 M290 624 H316.8 M290 630.3 H316.8 M316.8 561.8 H329.5 V586.2 H316.8 Z M323.15 561.8 V586.2 M829 518 H854.4 V562.5 H829 Z M829 524.3 H854.4 M829 530.6 H854.4 M829 536.9 H854.4 M829 543.2 H854.4 M829 549.5 H854.4 M829 555.8 H854.4 M798 562.5 H829 V586.2 H798 Z M804.3 562.5 V586.2 M810.6 562.5 V586.2 M816.9 562.5 V586.2 M823.2 562.5 V586.2",
    },
  },
};

export const FLOORS: Floor[] = ['upstairs', 'downstairs'];
